---
- name: debian | installing pre-reqs
  apt:
    name: ["python-mysqldb", "software-properties-common"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | adding mariadb repo keys
  apt_key:
    keyserver: "{{ mariadb_debian_repo_keyserver }}"
    id: "{{ mariadb_debian_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: mariadb_enable_mariadb_repo

- name: debian | adding mariadb repo
  apt_repository:
    repo: "{{ mariadb_debian_repo }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: mariadb_enable_mariadb_repo

- include: mysql_root_pw.yml

- name: debian | installing mariadb mysql
  apt:
    name: mariadb-server
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | configuring mariadb mysql
  template:
    src: etc/mysql/my.cnf.j2
    dest: /etc/mysql/my.cnf
  become: true
  notify: restart mysql

- name: debian | configuring client configuration
  template:
    src: etc/mysql/conf.d/client.cnf.j2
    dest: /etc/mysql/conf.d/client.cnf
    owner: root
    group: root
    mode: 0644
  become: true
  notify: restart mysql
